upload all changues
jordidh/multi-tenant-app pull request #19
Opened 2024-09-12 12:52 UTC by bernatbrunet

Created APIs for managing order, order_line, and customer entities.
	•	Developed an additional API for setting up test databases specifically used for testing purposes.
	•	Removed db_insert and replaced it with db_insert_test for testing workflows.
	•	Created and successfully tested automated tests for all the newly developed APIs.

2024-09-12 13:26 UTC, jordidh requested changes
There are some issues that has to be fixed

2024-09-12 13:26 UTC, jordidh commented on api/tenantdb.js
> +    // Add connection explicitly for tenant 999
This connection must use environtment variables

2024-09-12 13:26 UTC, jordidh commented on estructura_proyecto.txt
What is this file?

2024-09-12 13:26 UTC, jordidh commented on structure.txt
What is this file?

2024-09-12 13:26 UTC, jordidh commented on api/tenantdb.js
> +            host: db.host,
This environment variables must be specified in the env.example file

2024-09-12 13:26 UTC, jordidh commented on app.js
> -// Gets all databases from mysql and adds to the connectionMap with tenantdb.connectAll(dbs)
Where is this function?

2024-09-12 13:26 UTC, jordidh commented on routes/clean-db-test.js
> +            throw new Error('Couldn\'t insert values into db_test_insert.unit');
Must show databasename from environment variables

2024-09-12 13:26 UTC, jordidh commented on test/routes/v1/1_warehouse_spec.js
> +        if (locations.body.requestId) {
Why this if?

2024-09-12 13:26 UTC, jordidh commented on test/routes/v1/2_order_spec.js
> +        if (orders.body.requestId) {
Why this if?

2024-09-12 13:26 UTC, jordidh commented on test/routes/v1/4_customer_spec.js
> +            if (res.body.requestId) {
Why this if?

2024-09-19 12:30 UTC, bernatbrunet commented on app.js
> -// Gets all databases from mysql and adds to the connectionMap with tenantdb.connectAll(dbs)
The connectAll function is located in the api/tenantdb.js file.

2024-09-19 12:32 UTC, bernatbrunet commented on api/tenantdb.js
> +            host: db.host,
Problem solved.

2024-09-19 12:32 UTC, bernatbrunet commented on structure.txt
Problem solved.

2024-09-19 12:32 UTC, bernatbrunet commented on estructura_proyecto.txt
Problem solved.

2024-09-19 12:32 UTC, bernatbrunet commented on api/tenantdb.js
> +    // Add connection explicitly for tenant 999
Problem solved.

2024-09-19 12:41 UTC, bernatbrunet commented on routes/clean-db-test.js
> +            throw new Error('Couldn\'t insert values into db_test_insert.unit');
Problem solved.

2024-09-19 12:42 UTC, bernatbrunet commented on test/routes/v1/1_warehouse_spec.js
> +        if (locations.body.requestId) {
Problem solved.

2024-09-19 12:42 UTC, bernatbrunet commented on test/routes/v1/2_order_spec.js
> +        if (orders.body.requestId) {
Problem solved.

2024-09-19 12:42 UTC, bernatbrunet commented on test/routes/v1/4_customer_spec.js
> +            if (res.body.requestId) {
Problem solved.

2024-09-27 13:16 UTC, jordidh requested changes

2024-09-27 13:16 UTC, jordidh commented on app.js
> +                host: tenant.db_host || process.env.DB_HOST,
Delete environment variables

2024-09-27 13:25 UTC, jordidh approved these changes

2024-09-27 13:34 UTC, merged